### ISSUE TITLE
redis in hooks: TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by ivan** [ArchiveTeam/ArchiveBot#116]
9dibl3b6pr5il2qeqlgpnneal https://freeweibo.com/ crashed with:

```
200 OK http://tp3.sinaimg.cn/1670025294/50/5608587818/1
200 OK https://freeweibo.com/weibo/%E9%98%BF%E9%87%8C_%E6%B3%A2%E7%89%B9
200 OK http://ww4.sinaimg.cn/thumbnail/638a904ejw1e6i1f1vdygj20qo0zkq6z.jpg
200 OK http://ww4.sinaimg.cn/thumbnail/638a904ejw1e5r5onb8apj20m00cg40u.jpg
200 OK http://ww4.sinaimg.cn/large/638a904ejw1e6i1f1vdygj20qo0zkq6z.jpg
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/archivebot/ArchiveBot34/pipeline/archivebot/wpull/settings.py", line 191, in run
    self.process_messages(p)
  File "/home/archivebot/ArchiveBot34/pipeline/archivebot/wpull/settings.py", line 206, in process_messages
    msg = p.get_message(ignore_subscribe_messages=True)
  File "/home/archivebot/.local/lib/python3.4/site-packages/redis/client.py", line 2066, in get_message
    return self.handle_message(response, ignore_subscribe_messages)
  File "/home/archivebot/.local/lib/python3.4/site-packages/redis/client.py", line 2075, in handle_message
    message_type = nativestr(response[0])
TypeError: 'int' object is not subscriptable
```

**Comment by falconkirtaran** [comment]
We've not seen this in the past year or so, and it looks a lot like that was a redis client bug.  I can't readily find any evidence of it, but that we haven't seen it and it isn't even ours militates in favour of closing this.
