### ISSUE TITLE
Redis crashes in the log shipping thread causing RAM issues (aka. postmortem on the 2018-08-09 incident)

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ArchiveTeam/ArchiveBot#323]
On 2018-08-09, something happened on the control node which caused Redis to throw an error. This error was not caught in ArchiveBot, and this caused the thread sending logs to Redis to crash (below is an example from job 2tldvnvno8tzumwauaj6zoa08):

    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/home/archivebot/ArchiveBot/pipeline/archivebot/control.py", line 266, in ship_logs
        pipe.execute()
      File "/home/archivebot/.local/lib/python3.5/site-packages/redis/client.py", line 2578, in execute
        return execute(conn, stack, raise_on_error)
      File "/home/archivebot/.local/lib/python3.5/site-packages/redis/client.py", line 2519, in _execute_pipeline
        self.raise_first_error(commands, response)
      File "/home/archivebot/.local/lib/python3.5/site-packages/redis/client.py", line 2526, in raise_first_error
        raise r
      File "/home/archivebot/.local/lib/python3.5/site-packages/redis/client.py", line 2514, in _execute_pipeline
        self.parse_response(connection, args[0], **options))
      File "/home/archivebot/.local/lib/python3.5/site-packages/redis/client.py", line 2536, in parse_response
        self, connection, command_name, **options)
      File "/home/archivebot/.local/lib/python3.5/site-packages/redis/client.py", line 577, in parse_response
        response = connection.read_response()
      File "/home/archivebot/.local/lib/python3.5/site-packages/redis/connection.py", line 574, in read_response
        raise response
    redis.exceptions.ResponseError: Command # 1 (EVALSHA f6fda5256637da887e5745b23660c71a16a25ed0 1 2tldvnvno8tzumwauaj6zoa08 {"url": "https://lancasteronline.com/obituaries/jean-ross/article_2c56fd48-cad1-547f-bdda-68cf13c215a4.html", "wget_code": "OK", "is_warning": false, "is_error": false, "ts": 1533839662.075921, "response_code": 200, "type": "download"} updates 2tldvnvno8tzumwauaj6zoa08_log) of pipeline caused error: Error running script (call to f_f6fda5256637da887e5745b23660c71a16a25ed0): @user_script:7: @user_script: 7: -MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

A week later, on 2018-08-17, three jobs (all on different pipelines) were killed by the kernel's OOM killer because the machine ran out of RAM. The reason was the Redis code in `pipeline/archivebot/control.py`. ArchiveBot uses a Queue internally for storing the log lines that haven't been shipped to Redis yet. Because the thread consuming this queue crashed due to the issue on the control node, the queue started growing infinitely, eventually consuming all available memory. (It is not clear whether there were also jobs killed before 2018-08-17.)

There are two things here that I think need fixing:

1. Handle the exception so it doesn't crash the log shipper thread.
2. Limit the log queue size. When it's full, the oldest entry should just be dropped. (NB, the code already drops entries when it can't send them to Redis, so the lost log entries shouldn't be too much of a concern.)

**Comment by JustAnotherArchivist** [comment]
Workaround script which drains the queue and replaces the crashed log shipping thread: https://gist.github.com/JustAnotherArchivist/8f5ac42a9c03302f222af3a58a863468

**Comment by JustAnotherArchivist** [comment]
The same issue happened again today at 03:09 UTC.

This seems to happen when the forked Redis process which dumps the data to disk dies. Both on 2018-08-09 and today, this was caused by the OOM killer. In that sense, this is connected to #324 and caused by the dashboard memory leak.
